 spring:
  profiles:
     active: production
 feign:
  url: http://www.tix.com
  client:
    config:
      feignName:
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder
